name: aeroport_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.7.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  animated_bottom_navigation_bar: ^1.3.0
  iconsax: ^0.0.8
  get: ^4.6.6
  crypto: ^3.0.2
  intl: ^0.19.0
  # optional: for maps or LBS if you later enable
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  collection: ^1.17.0
  timezone: ^0.9.2
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.1.2 # Pustaka untuk mengambil gambar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1  # <-- TAMBAHKAN INI
  build_runner: ^2.4.7
  analyzer: ^6.4.1

## dependency_overrides:
##  flutter_local_notifications: 16.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
